---
title: "Simulation von Zufallszahlen"
subtitle: "Vorlesung: Computerintensive Methoden SS 2017"
author: 
- "Bernhard Preisler (734631)"
- "[Hendrik Pfaff](http://hendrik-pfaff.de) (725837)"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
tags: [Vorlesung, Computational Statistics, Zufallszahlen, Zufallsvariablen, Simulation]
output:
  pdf_document:
    toc: true
---

\newpage
# Motiviation
- Zufallszahlen spielen heutzutage eine wichtige Rolle in Wissenschaft, Technik und Industrie 
- Die Erzeugung von Zufälligkeiten in einem Computer (aka: deterministischer Automat) stellt eine besondere Herausforderung dar, da jede Operation durch die Vorherige definiert wird und daher (theoretisch) berechenbar ist.

# Definitionen
Um möglichen Verwirrungen vorzubeugen, werden in diesen Kapitel Begrifflichkeiten in Bezug aus das Thema Simulation von Zufallszahlen eingeführt und abgegrenzt.

## Zufallsvariablen \& Zufallszahlen
Eine \textbf{Zufallsvariable} ist eine Variable, die die Wahrscheinlichkeit eines noch nicht durchgeführten Experiments beschreibt. Beispielsweise kann solch eine Zufallsvariable den Wurf eines fairen sechseitigen Würfels beschreiben. Die Wahrscheinlichkeit für den Ausgang eines bestimmten Ergebnis ist in diesem Beispiel gleichverteilt. Das Ergebnis wird als \textbf{Zufallszahl} beschrieben. Mathematisch wird eine Zufallsvariable mit einem Großbuchstaben $X$, $Y$, $Z$ und eine Zufallszahl mit einen Kleinbuchstaben $x$ betitelt.

## Nichtdeterministische \& deterministische Zufallsgeneratoren
Der Ausgang einer Funktion verändert sich bei einer gleichbleibenden Eingabe nicht. Demnach lässt sich eine komplett zufällige Funktion rein durch Software nur schwer realisieren. Eine Möglichkeit dieses Problem zu lösen sind die Außeneinwirkungen, die die Möglichkeit bieten Funktionen mit dem gleichen Eingabewerten zu unterschiedlichen Ergebnissen zu führen. Dieses Prinzip nennt sich \emph{Nichtdeterminismus} und diese Art von Generatoren werden die \textbf{nichtdeterministische Zufallsgenerator} genannt.

* Hardwarekomponente, die auf physikalische Prozesse zurückgreift um Zahlen zu generieren
* Atmosphärenrauschen (wie analoges Radio, das nicht auf einen Sender abgestimmt ist)
* CCD-Sensorrauschen (mit einer schlechten (z. B. Handy-) Kamera in einem dunklen Raum fotografieren und daraus Zufallszahlen ableiten)
* Schwankung der tatsächlichen Zeitdauer einer mit einem Zeitgeber („Timer“) gemessenen Zeitdauer.
* Spannungsschwankungen an einer Z-Diode.
* Allerdings müssen physikalische Beobachtunge (um die Zahlen zu generieren) in einem angemessen großen Abstand zueinander erfolgen um Unabhängigkeit zu gewährleisten

Demnach zeichnen sich die \textbf{deterministischen Zufallsgeneratoren} dadurch aus, dass bei gleicher Eingabe immer der selber Ausgang berechnet wird.

* Nur die Erzeugung von Pseudozufallszahlen möglich


## Pseudozufall
Pseudozufall ...

## Güte des Zufallszahlengenerators

# Quellen
Hier kommen Quellen.




